import type { PathAnchor, ReferenceTemplate } from '../types/guitar';

// 1. S-Style Blueprint Anchors (Iconic Stratocaster Blueprint Spline)
export const S_STYLE_ANCHORS: PathAnchor[] = [
  {
    id: 's_pocket_left',
    position: { x: -27.78, y: 0 },
    handleOut: { x: -20, y: -20 },
    handleMode: 'smooth',
    locked: true,
    semanticRole: 'neck_pocket_left',
  },
  {
    id: 's_horn_scoop_left',
    position: { x: -50, y: -25 },
    handleIn: { x: 10, y: 15 },
    handleOut: { x: -20, y: -30 },
    handleMode: 'smooth',
  },
  {
    id: 's_upper_horn_tip',
    position: { x: -125, y: -95 },
    handleIn: { x: 25, y: -35 },
    handleOut: { x: -25, y: 35 },
    handleMode: 'smooth',
    semanticRole: 'upper_horn_left',
  },
  {
    id: 's_upper_bout_outer_left',
    position: { x: -140, y: 10 },
    handleIn: { x: -5, y: -35 },
    handleOut: { x: 5, y: 40 },
    handleMode: 'smooth',
  },
  {
    id: 's_waist_left',
    position: { x: -118, y: 130 },
    handleIn: { x: 10, y: -35 },
    handleOut: { x: -15, y: 55 },
    handleMode: 'smooth',
    semanticRole: 'waist_left',
  },
  {
    id: 's_lower_bout_left',
    position: { x: -162, y: 280 },
    handleIn: { x: -15, y: -45 },
    handleOut: { x: 30, y: 75 },
    handleMode: 'smooth',
    semanticRole: 'lower_bout_left',
  },
  {
    id: 's_lower_bout_bottom_left',
    position: { x: -125, y: 385 },
    handleIn: { x: -35, y: -20 },
    handleOut: { x: 40, y: 20 },
    handleMode: 'smooth',
  },
  {
    id: 's_tail_center',
    position: { x: 0, y: 405 },
    handleIn: { x: -60, y: 0 },
    handleOut: { x: 60, y: 0 },
    handleMode: 'symmetric',
    semanticRole: 'tail_center',
  },
  {
    id: 's_lower_bout_bottom_right',
    position: { x: 125, y: 385 },
    handleIn: { x: -40, y: 20 },
    handleOut: { x: 35, y: -20 },
    handleMode: 'smooth',
  },
  {
    id: 's_lower_bout_right',
    position: { x: 162, y: 280 },
    handleIn: { x: -30, y: 75 },
    handleOut: { x: 15, y: -45 },
    handleMode: 'smooth',
    semanticRole: 'lower_bout_right',
  },
  {
    id: 's_waist_right',
    position: { x: 118, y: 130 },
    handleIn: { x: 15, y: 55 },
    handleOut: { x: -10, y: -35 },
    handleMode: 'smooth',
    semanticRole: 'waist_right',
  },
  {
    id: 's_upper_bout_outer_right',
    position: { x: 135, y: 10 },
    handleIn: { x: 5, y: 40 },
    handleOut: { x: -5, y: -35 },
    handleMode: 'smooth',
  },
  {
    id: 's_treble_horn_tip',
    position: { x: 105, y: -55 },
    handleIn: { x: 25, y: 35 },
    handleOut: { x: -25, y: -35 },
    handleMode: 'smooth',
    semanticRole: 'upper_horn_right',
  },
  {
    id: 's_horn_scoop_right',
    position: { x: 42, y: -20 },
    handleIn: { x: 15, y: -25 },
    handleOut: { x: -10, y: 10 },
    handleMode: 'smooth',
  },
  {
    id: 's_pocket_right',
    position: { x: 27.78, y: 0 },
    handleIn: { x: 15, y: -15 },
    handleMode: 'smooth',
    locked: true,
    semanticRole: 'neck_pocket_right',
  },
];

// 2. T-Style Blueprint Anchors (Iconic Telecaster Blueprint Spline)
export const T_STYLE_ANCHORS: PathAnchor[] = [
  {
    id: 't_pocket_left',
    position: { x: -27.78, y: 0 },
    handleOut: { x: -30, y: 0 },
    handleMode: 'smooth',
    locked: true,
    semanticRole: 'neck_pocket_left',
  },
  {
    id: 't_shoulder_left',
    position: { x: -115, y: -15 },
    handleIn: { x: 25, y: -10 },
    handleOut: { x: -20, y: 15 },
    handleMode: 'smooth',
    semanticRole: 'upper_horn_left',
  },
  {
    id: 't_upper_bout_left',
    position: { x: -135, y: 30 },
    handleIn: { x: -5, y: -25 },
    handleOut: { x: 5, y: 45 },
    handleMode: 'smooth',
  },
  {
    id: 't_waist_left',
    position: { x: -130, y: 150 },
    handleIn: { x: 5, y: -40 },
    handleOut: { x: -10, y: 60 },
    handleMode: 'smooth',
    semanticRole: 'waist_left',
  },
  {
    id: 't_lower_bout_left',
    position: { x: -164, y: 290 },
    handleIn: { x: -10, y: -50 },
    handleOut: { x: 25, y: 80 },
    handleMode: 'smooth',
    semanticRole: 'lower_bout_left',
  },
  {
    id: 't_lower_bout_bottom_left',
    position: { x: -130, y: 390 },
    handleIn: { x: -35, y: -20 },
    handleOut: { x: 45, y: 10 },
    handleMode: 'smooth',
  },
  {
    id: 't_tail_center',
    position: { x: 0, y: 400 },
    handleIn: { x: -60, y: 0 },
    handleOut: { x: 60, y: 0 },
    handleMode: 'symmetric',
    semanticRole: 'tail_center',
  },
  {
    id: 't_lower_bout_bottom_right',
    position: { x: 130, y: 390 },
    handleIn: { x: -45, y: 10 },
    handleOut: { x: 35, y: -20 },
    handleMode: 'smooth',
  },
  {
    id: 't_lower_bout_right',
    position: { x: 164, y: 290 },
    handleIn: { x: -25, y: 80 },
    handleOut: { x: 10, y: -50 },
    handleMode: 'smooth',
    semanticRole: 'lower_bout_right',
  },
  {
    id: 't_waist_right',
    position: { x: 130, y: 150 },
    handleIn: { x: 10, y: 60 },
    handleOut: { x: -5, y: -40 },
    handleMode: 'smooth',
    semanticRole: 'waist_right',
  },
  {
    id: 't_cutaway_outer_right',
    position: { x: 135, y: 65 },
    handleIn: { x: 5, y: 45 },
    handleOut: { x: -15, y: -20 },
    handleMode: 'smooth',
  },
  {
    id: 't_cutaway_horn_tip_right',
    position: { x: 95, y: 30 },
    handleIn: { x: 25, y: 15 },
    handleOut: { x: -20, y: -10 },
    handleMode: 'smooth',
    semanticRole: 'upper_horn_right',
  },
  {
    id: 't_cutaway_inner_scoop_right',
    position: { x: 40, y: 15 },
    handleIn: { x: 15, y: 10 },
    handleOut: { x: -5, y: -5 },
    handleMode: 'smooth',
  },
  {
    id: 't_pocket_right',
    position: { x: 27.78, y: 0 },
    handleIn: { x: 15, y: 0 },
    handleMode: 'smooth',
    locked: true,
    semanticRole: 'neck_pocket_right',
  },
];

// 3. Single-Cut Blueprint Anchors (Iconic Les Paul Blueprint Spline)
export const SINGLE_CUT_ANCHORS: PathAnchor[] = [
  {
    id: 'sc_pocket_left',
    position: { x: -19.05, y: 0 },
    handleOut: { x: -40, y: 5 },
    handleMode: 'smooth',
    locked: true,
    semanticRole: 'neck_pocket_left',
  },
  {
    id: 'sc_upper_shoulder',
    position: { x: -85, y: 30 },
    handleIn: { x: 25, y: -15 },
    handleOut: { x: -25, y: 15 },
    handleMode: 'smooth',
  },
  {
    id: 'sc_upper_bout',
    position: { x: -118, y: 105 },
    handleIn: { x: 0, y: -40 },
    handleOut: { x: 0, y: 45 },
    handleMode: 'smooth',
    semanticRole: 'upper_horn_left',
  },
  {
    id: 'sc_waist_left',
    position: { x: -110, y: 195 },
    handleIn: { x: -5, y: -35 },
    handleOut: { x: -5, y: 40 },
    handleMode: 'smooth',
    semanticRole: 'waist_left',
  },
  {
    id: 'sc_lower_bout_left',
    position: { x: -165, y: 310 },
    handleIn: { x: -15, y: -45 },
    handleOut: { x: 25, y: 75 },
    handleMode: 'smooth',
    semanticRole: 'lower_bout_left',
  },
  {
    id: 'sc_lower_bout_bottom_left',
    position: { x: -130, y: 395 },
    handleIn: { x: -35, y: -25 },
    handleOut: { x: 45, y: 25 },
    handleMode: 'smooth',
  },
  {
    id: 'sc_tail_center',
    position: { x: 0, y: 420 },
    handleIn: { x: -60, y: 0 },
    handleOut: { x: 60, y: 0 },
    handleMode: 'symmetric',
    semanticRole: 'tail_center',
  },
  {
    id: 'sc_lower_bout_bottom_right',
    position: { x: 130, y: 395 },
    handleIn: { x: -45, y: 25 },
    handleOut: { x: 35, y: -25 },
    handleMode: 'smooth',
  },
  {
    id: 'sc_lower_bout_right',
    position: { x: 165, y: 310 },
    handleIn: { x: -25, y: 75 },
    handleOut: { x: 15, y: -45 },
    handleMode: 'smooth',
    semanticRole: 'lower_bout_right',
  },
  {
    id: 'sc_waist_right',
    position: { x: 110, y: 195 },
    handleIn: { x: 5, y: 40 },
    handleOut: { x: 5, y: -35 },
    handleMode: 'smooth',
    semanticRole: 'waist_right',
  },
  {
    id: 'sc_cutaway_horn_tip',
    position: { x: 110, y: 85 },
    handleIn: { x: 15, y: 35 },
    handleOut: { x: -25, y: -25 },
    handleMode: 'smooth',
    semanticRole: 'upper_horn_right',
  },
  {
    id: 'sc_cutaway_inner_scoop',
    position: { x: 28, y: 22 },
    handleIn: { x: 15, y: 10 },
    handleOut: { x: -5, y: -5 },
    handleMode: 'smooth',
  },
  {
    id: 'sc_pocket_right',
    position: { x: 19.05, y: 0 },
    handleIn: { x: 5, y: 0 },
    handleMode: 'smooth',
    locked: true,
    semanticRole: 'neck_pocket_right',
  },
];

// 4. Double-Cut SG Blueprint Anchors (Iconic Gibson/Yamaha SG Blueprint Spline)
export const SG_STYLE_ANCHORS: PathAnchor[] = [
  {
    id: 'sg_pocket_left',
    position: { x: -19.05, y: 0 },
    handleOut: { x: -15, y: -15 },
    handleMode: 'smooth',
    locked: true,
    semanticRole: 'neck_pocket_left',
  },
  {
    id: 'sg_horn_scoop_left',
    position: { x: -38, y: -15 },
    handleIn: { x: 10, y: 10 },
    handleOut: { x: -15, y: -25 },
    handleMode: 'smooth',
  },
  {
    id: 'sg_upper_horn_tip_left',
    position: { x: -110, y: -85 },
    handleIn: { x: 25, y: -35 },
    handleOut: { x: -20, y: 35 },
    handleMode: 'smooth',
    semanticRole: 'upper_horn_left',
  },
  {
    id: 'sg_upper_bout_outer_left',
    position: { x: -140, y: 10 },
    handleIn: { x: -5, y: -35 },
    handleOut: { x: 5, y: 35 },
    handleMode: 'smooth',
  },
  {
    id: 'sg_waist_left',
    position: { x: -122, y: 110 },
    handleIn: { x: -5, y: -35 },
    handleOut: { x: -20, y: 50 },
    handleMode: 'smooth',
    semanticRole: 'waist_left',
  },
  {
    id: 'sg_lower_bout_left',
    position: { x: -160, y: 260 },
    handleIn: { x: -15, y: -45 },
    handleOut: { x: 35, y: 80 },
    handleMode: 'smooth',
    semanticRole: 'lower_bout_left',
  },
  {
    id: 'sg_lower_bout_bottom_left',
    position: { x: -125, y: 350 },
    handleIn: { x: -35, y: -20 },
    handleOut: { x: 40, y: 15 },
    handleMode: 'smooth',
  },
  {
    id: 'sg_tail_center',
    position: { x: 0, y: 365 },
    handleIn: { x: -60, y: 0 },
    handleOut: { x: 60, y: 0 },
    handleMode: 'symmetric',
    semanticRole: 'tail_center',
  },
  {
    id: 'sg_lower_bout_bottom_right',
    position: { x: 125, y: 350 },
    handleIn: { x: -40, y: 15 },
    handleOut: { x: 35, y: -20 },
    handleMode: 'smooth',
  },
  {
    id: 'sg_lower_bout_right',
    position: { x: 160, y: 260 },
    handleIn: { x: -35, y: 80 },
    handleOut: { x: 15, y: -45 },
    handleMode: 'smooth',
    semanticRole: 'lower_bout_right',
  },
  {
    id: 'sg_waist_right',
    position: { x: 122, y: 110 },
    handleIn: { x: 20, y: 50 },
    handleOut: { x: -5, y: -35 },
    handleMode: 'smooth',
    semanticRole: 'waist_right',
  },
  {
    id: 'sg_upper_bout_outer_right',
    position: { x: 140, y: 10 },
    handleIn: { x: 5, y: 35 },
    handleOut: { x: -5, y: -35 },
    handleMode: 'smooth',
  },
  {
    id: 'sg_upper_horn_tip_right',
    position: { x: 110, y: -85 },
    handleIn: { x: 20, y: 35 },
    handleOut: { x: -25, y: -35 },
    handleMode: 'smooth',
    semanticRole: 'upper_horn_right',
  },
  {
    id: 'sg_horn_scoop_right',
    position: { x: 38, y: -15 },
    handleIn: { x: 15, y: -25 },
    handleOut: { x: -10, y: 10 },
    handleMode: 'smooth',
  },
  {
    id: 'sg_pocket_right',
    position: { x: 19.05, y: 0 },
    handleIn: { x: 15, y: -15 },
    handleMode: 'smooth',
    locked: true,
    semanticRole: 'neck_pocket_right',
  },
];

export const REFERENCE_TEMPLATES: Record<string, ReferenceTemplate> = {
  single_cut: {
    id: 'single_cut',
    name: 'Single-Cut Vintage',
    description: 'Classic single-cut Mahogany body with dual humbuckers and Tune-O-Matic bridge.',
    category: 'Single-Cut',
    neckPresetId: 'gibson_lp_22',
    bridgePresetId: 'tune_o_matic',
    defaultAnchors: SINGLE_CUT_ANCHORS,
    defaultPickups: [
      { id: 'p_neck', type: 'humbucker', offsetYMm: 115, offsetXMm: 0, angleDegrees: 0, widthMm: 70, heightMm: 38 },
      { id: 'p_bridge', type: 'humbucker', offsetYMm: 205, offsetXMm: 0, angleDegrees: 0, widthMm: 70, heightMm: 38 },
    ],
  },
  sg_style: {
    id: 'sg_style',
    name: 'Double-Cut SG Vintage',
    description: 'Symmetric double-cutaway Vintage SG body (Gibson/Yamaha style) with bevel contours.',
    category: 'Single-Cut',
    neckPresetId: 'gibson_lp_22',
    bridgePresetId: 'tune_o_matic',
    defaultAnchors: SG_STYLE_ANCHORS,
    defaultPickups: [
      { id: 'p_neck', type: 'humbucker', offsetYMm: 115, offsetXMm: 0, angleDegrees: 0, widthMm: 70, heightMm: 38 },
      { id: 'p_bridge', type: 'humbucker', offsetYMm: 205, offsetXMm: 0, angleDegrees: 0, widthMm: 70, heightMm: 38 },
    ],
  },
  s_style: {
    id: 's_style',
    name: 'S-Style Standard',
    description: 'Double cutaway body with contoured waist and upper horns.',
    category: 'S-Style',
    neckPresetId: 'fender_strat_21',
    bridgePresetId: 'tremolo_strat',
    defaultAnchors: S_STYLE_ANCHORS,
    defaultPickups: [
      { id: 'p_neck', type: 'single_coil', offsetYMm: 110, offsetXMm: 0, angleDegrees: 0, widthMm: 70, heightMm: 18 },
      { id: 'p_middle', type: 'single_coil', offsetYMm: 155, offsetXMm: 0, angleDegrees: 0, widthMm: 70, heightMm: 18 },
      { id: 'p_bridge', type: 'single_coil', offsetYMm: 200, offsetXMm: 0, angleDegrees: -10, widthMm: 70, heightMm: 18 },
    ],
  },
  t_style: {
    id: 't_style',
    name: 'T-Style Standard',
    description: 'Single cutaway solid body with flat edge profile and classic bridge plate.',
    category: 'T-Style',
    neckPresetId: 'fender_tele_22',
    bridgePresetId: 'tele_bridge_plate',
    defaultAnchors: T_STYLE_ANCHORS,
    defaultPickups: [
      { id: 'p_neck', type: 'tele_neck', offsetYMm: 120, offsetXMm: 0, angleDegrees: 0, widthMm: 65, heightMm: 15 },
      { id: 'p_bridge', type: 'tele_bridge', offsetYMm: 205, offsetXMm: 0, angleDegrees: -11, widthMm: 73, heightMm: 20 },
    ],
  },
};
