/**
 * Generates the landing page's display plan from the canonical printable one.
 *
 * These two files exist because the hero and the printer want opposite things.
 *
 * The plan's strokes are physical millimetres. The hero renders it at roughly
 * 0.8 px/mm, so the app's normal 0.4mm body outline lands near 0.3 CSS px and
 * the drawing reads as a ghost. Legibility there wants fat lines.
 *
 * But the downloaded file is the thing someone prints 1:1 and cuts to, and a
 * line you cut to the middle of is an error budget: at 0.4mm the ambiguity is
 * a third of a millimetre, at 1.2mm it is over a millimetre. Accuracy there
 * wants thin lines.
 *
 * So the source of truth stays the printable plan, and this script derives a
 * display-only copy: same geometry, heavier strokes, and no project payload
 * (roughly 34KB of base64 the hero never reads).
 *
 *   npm run marketing:plan
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const SOURCE = resolve(root, 'public/marketing/custom-s-style-plan.axe.svg');
const OUTPUT = resolve(root, 'public/marketing/custom-s-style-plan-display.svg');

/**
 * Display stroke width in millimetres, per drawing class.
 *
 * These are chosen against the measured hero scale rather than by eye. The
 * sheet renders at ~0.804 px/mm on desktop and ~0.722 px/mm at 375px, so a
 * stroke needs roughly 1.25mm to clear 1 CSS px on both. Primary structure -
 * the outline, pocket, routes and calibration box - is set above that line;
 * dashed secondary guides sit just under it, which is the right hierarchy
 * anyway.
 *
 * Nothing here costs print accuracy, because this file is never printed. That
 * is the whole reason it exists separately.
 */
const DISPLAY_STROKE_MM: Record<string, number> = {
  'body-line': 1.7,
  'edge-inset': 1.2,
  'neck-pocket': 1.5,
  'pickup-rout': 1.4,
  'bridge-rout': 1.5,
  'back-route': 1.2,
  'front-route': 1.3,
  pickguard: 1.4,
  'center-axis': 1.2,
  'calibration-box': 1.5,
  'band-rule': 0.9,
};

/** Dashes are re-cut to suit the heavier stroke; a 3,2 dash reads as solid at 1.2mm. */
const DISPLAY_DASH_MM: Record<string, string> = {
  'edge-inset': '5.5,2.4',
  'back-route': '2.8,1.8',
  'center-axis': '7,5',
  'calibration-box': '4.5,3.5',
};

const source = readFileSync(SOURCE, 'utf8');

// Drop the project payload: the display copy is for looking at, and the
// download link serves the real file.
const metadata = /<metadata\b[^>]*>[\s\S]*?<\/metadata>/;
if (!metadata.test(source)) throw new Error(`no <metadata> block to strip in ${SOURCE}`);
let out = source.replace(
  metadata,
  '<!-- Project payload omitted; the printable .axe.svg carries it. -->',
);

// Rewrite the stroke width (and dash, where set) on each class in the <style>
// block. Editing the stylesheet rather than the elements keeps the geometry
// byte-for-byte identical to the printable plan.
for (const [cls, mm] of Object.entries(DISPLAY_STROKE_MM)) {
  const rule = new RegExp(`(\\.${cls}\\s*\\{[^}]*?stroke-width:\\s*)[0-9.]+`);
  if (!rule.test(out)) throw new Error(`no .${cls} rule with a stroke-width in ${SOURCE}`);
  out = out.replace(rule, `$1${mm}`);

  const dash = DISPLAY_DASH_MM[cls];
  if (dash) {
    const dashRule = new RegExp(`(\\.${cls}\\s*\\{[^}]*?stroke-dasharray:\\s*)[0-9.,\\s]+`);
    if (!dashRule.test(out)) throw new Error(`no .${cls} rule with a stroke-dasharray`);
    out = out.replace(dashRule, `$1${dash}`);
  }
}

out = out.replace(
  '<svg',
  '<!-- Generated by scripts/build-marketing-plan.ts from custom-s-style-plan.axe.svg.\n'
    + '     Geometry verbatim; stroke weights raised for screen. Do not edit by hand. -->\n<svg',
);

writeFileSync(OUTPUT, out, 'utf8');

const kb = (n: number) => `${(n / 1024).toFixed(1)}KB`;
console.log(
  `build-marketing-plan: ${OUTPUT.replace(`${root}/`, '')} (${kb(source.length)} -> ${kb(out.length)})`,
);
