/**
 * Derives the marketing hero's display plan from the app's real S-style export.
 *
 * The landing page's whole argument is that the printable plan is the proof, so
 * the hero must show the app's actual output geometry - not a redrawn mockup.
 * But the real file is authored for paper: strokes are specified in physical
 * millimetres (0.4mm outline) and the sheet is 364 x 656mm. Scaled into a hero
 * that is ~380 CSS px wide, 0.4mm lands at roughly 0.4 CSS px and the drawing
 * renders as a sub-pixel ghost.
 *
 * This script copies the geometry verbatim and rewrites only presentation:
 * stroke widths and label sizes are multiplied so every line clears 1 CSS px at
 * hero scale. It also drops the base64 project payload (~20KB the hero never
 * reads) and the in-app editing disclaimer, which is addressed to someone who
 * has already downloaded the file.
 *
 * The download link on the page still points at the real .axe.svg. This asset
 * is for looking at; that one is for building from.
 *
 *   npm run marketing:plan
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const SOURCE = resolve(root, 'src/constants/blueprints/s_style.axe.svg');
const OUTPUT = resolve(root, 'public/marketing/s-style-plan.svg');

/**
 * Display stroke widths in millimetres. The hero renders the plan at roughly
 * 1.05 px/mm, so these are chosen to land at ~1.7px for the body outline down
 * to ~0.8px for guides - a readable line hierarchy rather than a uniform smear.
 */
const DISPLAY_STYLE = `
.outline{fill:none;stroke:#14161c;stroke-width:1.7;stroke-linejoin:round}
.edge-inset{fill:none;stroke:#6d6a61;stroke-width:1.0;stroke-dasharray:7 4}
.rout{fill:none;stroke:#14161c;stroke-width:1.1}
.guide{fill:none;stroke:#a8a49a;stroke-width:0.8;stroke-dasharray:9 5}
.mounting-hole{fill:#14161c;stroke:none}
.cal{fill:none;stroke:#14161c;stroke-width:1.4}
.label{font-family:'JetBrains Mono',ui-monospace,monospace;font-size:11px;fill:#14161c}
`.trim();

const source = readFileSync(SOURCE, 'utf8');

// Keep the root element (it carries the true physical width/height/viewBox)
// and everything from the <style> block onward; drop <metadata>.
const openTag = source.match(/<svg\b[^>]*>/)?.[0];
if (!openTag) throw new Error('could not find the <svg> open tag in the source export');

const styleStart = source.indexOf('<style>');
if (styleStart === -1) throw new Error('could not find the <style> block in the source export');
const body = source.slice(source.indexOf('</style>') + '</style>'.length, source.lastIndexOf('</svg>'));

// The disclaimer speaks to someone editing a downloaded file; it has no job here.
const withoutDisclaimer = body.replace(/\s*<text class="disclaimer"[\s\S]*?<\/text>/g, '');

// Shorten the calibration caption: at hero scale the full paper sentence needs
// more width than the sheet has, and the page states the print check in its own
// copy anyway.
const withCaption = withoutDisclaimer.replace(
  /(<text class="label"[^>]*>)[\s\S]*?(<\/text>)/,
  '$1100 mm calibration square$2',
);

const output = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/build-marketing-plan.ts from src/constants/blueprints/s_style.axe.svg.
     Geometry is verbatim; only stroke weights and label sizes are scaled for screen. Do not edit by hand. -->
${openTag}
<title>S-Style Standard body plan exported by Axe Shaper</title>
<style>
${DISPLAY_STYLE}
</style>${withCaption}
</svg>
`;

writeFileSync(OUTPUT, output, 'utf8');

const before = (source.length / 1024).toFixed(1);
const after = (output.length / 1024).toFixed(1);
console.log(`build-marketing-plan: ${OUTPUT.replace(`${root}/`, '')} (${before}KB -> ${after}KB)`);
